version: '2'
services:
  mysql:
    build:
      dockerfile: mysqlDockerfile
      context: .
    container_name: mob-db
    volumes:
      - db:/application
#      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: always
  website:
    hostname: mob.local
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - C:\Users\Honza\projects\nette-mob\src:/var/www/html/
    environment:
    - APACHE_DOC_ROOT=/var/www/html/www
    ports:
      - 9090:80
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 9191:80
    environment:
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:.sweetpwd.
      - PMA_HOST:mysql
    depends_on:
      - mysql
volumes:
  db:
    external:
      name: sandbox

